### ISSUE TITLE
MTrack2 vs trackpy

### ISSUE THREAD

**Issue by nerduno** [soft-matter/trackpy#211]
I'm curious how trackpy compares to ImageJ's MTrack2.  In particular how does trackpy handle  disappearing and appearing particles?

Thanks,
Aaron

**Comment by danielballan** [comment]
I am not familiar with MTrack2, but we use the Crocker--Grier algorithm (and elaborations thereon) described in [this paper](http://physics.nyu.edu/grierlab/methods/methods.html).

**Comment by nkeim** [comment]
I don't think any of us is familiar with MTrack2. However, looking at their documentation, they have a less sophisticated (but still useful) way of dealing with ambiguous situations. When forced to choose, MTrack2 always chooses the nearest particle. The Crocker-Grier algorithm in trackpy doesn't minimize displacements locally (i.e. the nearest particle), but effectively minimizes displacements *globally*.

Additionally, you can look at the "memory" feature, which allows a particle to temporarily disappear, then reappear, and still be considered part of the same track.

Also: I use and like ImageJ because point-and-click functionality is "baked in," but Python is an excellent supplement to it. It is both general-purpose, and widely used for all kinds of quantitative science. You give up some of the point-and-click simplicity of ImageJ, but gain an interactive environment that is very customizable and extensible, and has excellent numerical, plotting, and import/export capabilities.

**Comment by nerduno** [comment]
Thanks for the very helpful information. I'm going to give trackpy a try.

**Comment by nkeim** [comment]
Glad to hear it! The tutorials and docs assume some basic knowledge of Python and some willingness to learn about DataFrames, but other than that they are meant for a wide audience, so please let us know if you find problems with them. We recommend that you start with the IPython Notebook interface; even if you are unfamiliar with it, it is a great way to learn.

**Comment by alexlib** [comment]
sorry to disturb, just wonder if you might consider trying the tracker from OpenPTV project? it's a fluid mechanics concept developed mainly for 3D turbulent flows, with all the calibration, photogrammetry, etc. see www.openptv.net

what we actually like a lot is your way to work with Pandas and HDF and we'll probably one day try to interface openptv to your great project, i.e. the user will collect images, then use the data format translator and then trackpy. Sometimes we need to do also 2D tracking or 3D tracking with small and random displacements.

**Comment by nkeim** [comment]
Thanks, @alexlib . OpenPTV looks very impressive, and it would be great if users could mix and match algorithms as needed.
