### ISSUE TITLE
A Faster Bandpass

### ISSUE THREAD

**Issue by danielballan** [soft-matter/trackpy#219]
[This notebook](http://nbviewer.ipython.org/urls/dl.dropbox.com/s/5cfyj0b046wq3ny/Making%20Bandpass%20Faster.ipynb?dl=0) benchmarks several different implementations of `bandpass`. I arrived at one that is twice as fast as trackpy's current implementation and up to 4X as fast with reasonable compromises in accuracy.

@nkeim, @caspervdw, @tacaswell and anyone else who is interested, would you run this notebook locally and confirm my timings? If this is correct and reproducible, I will make a PR to replace the current bandpass.

Unfortunately, the winning implementation does not allow us to hook into FFTW. Taking the long view, I don't want to completely blow away our work with FFTW even if it turns out to be slower. Instead, we can maintain several functions that give identical results, making `preprocessing.py` into a (very boring) research experiment on bandpass implementations in Python. The fastest one will be used by `locate(..., preprocess=True)`, but the others will be maintained for tinkering or future improvement.

**Comment by caspervdw** [comment]
This looks great!! I will run it and report the benchmarks on my windows box.

**Comment by nkeim** [comment]
Fantastic! I'd been waiting all day to try this for myself. It looks like you had some of your best ideas toward the end (as always happens), because I had to make some edits to get the notebook to run. So I'm sharing [my modified version](http://nbviewer.ipython.org/gist/nkeim/cb77b01385e3a1e39a7d). I adjusted the sample pool down to 200 images; 7.6 GB was a more comfortable fit on my MacBook.

I'm happy to report that the version with `gaussian_filter()` also consistently won on my Mac, by similar margins. Interestingly enough, the presence/absence of MKL seemed to make no difference — maybe numpy natively makes good use of SIMD?

Anyhow, this is just thrilling! This will put a big dent in the feature-finding time. I agree with your idea to have multiple implementations in `preprocessing.py`, just like we have multiple implementations of the subnet linker.

The biggest pain of adding this to trackpy will be changing the docs regarding FFTW. The performance tutorial can also suggest truncation as an additional speedup. I'd be happy to help with those changes if you'd like.

**Comment by danielballan** [comment]
Thanks. Yes, it occurred to me that documenting this will be tricky. FFTW becomes a *very* optional dependency. @nkeim I'll take you up on your offer to help. I'll start on `preprocessing.py` if you start on the performance tutorial.

But I'll wait to hear if non-OSX users report the same gains. I don't know how widely FFTW's performance varies between these architectures.

**Comment by caspervdw** [comment]
I ran the notebook and got similar results on my Win64 computer. Fantastic!!

Concerning the FFTW implementation: if this code supersedes the FFTW code, this would not throw away our work on FFTW. The code will stay in the git history anyway for future reference. Most users will not be interested in this code, as the new one is a lot faster and has the same functionality. If people would want to do any tinkering with old codes, they could find the code in the git history. A reference in the docs would be useful.

So I would vote for dropping the FFTW dependency, it is a good thing to keep the number of dependencies as low as possible and the code as slim as possible.

**Comment by nkeim** [comment]
I hadn't thought of referencing the other implementation(s) in the docs. That would take care of the educational/research benefit of having multiple implementations, while saving us from having to maintain and wade through vestigial code.

However, I'll bring up one other reason to keep the old version around, at least for a couple more releases: testing. The new code may look OK and pass all our unit tests, but as we've seen before, that is not an iron-clad guarantee of correctness in all real-world situations. If we, or a user, ever has reason to question the new bandpass, I think the whole project would benefit if they could easily check it against the old version right then and there.

**Comment by nkeim** [comment]
That being said, in the case of our use of FFTW specifically, I have nothing to counter @caspervdw 's argument for removing it.

**Comment by danielballan** [comment]
Good! @tacaswell reports that he sees similar speed gains in Linux.

I think it would be better to keep the old bandpass somewhere that is programmatically accessible in trackpy -- at least for one more release. Alternative implementations could be relegated to "developer code," not imported by default, and the optional FFTW dependency could be mentioned in the relevant docstring (and API docs) but nowhere in the installation instructions. Thoughts?

Either way, we can definitely remove the nasty logic that switches between FFTW and numpy. In my opinion, *that* code is the heart of the maintenance headache, and we could remove it by splitting the numpy and FFTW code paths into separate functions: `bandpass` (improved numpy implementation), `bandpass_legacy` (current numpy implementation), and `bandpass_legacy_fftw`.

**Comment by caspervdw** [comment]
I agree with your approach @danielballan, we can keep it in for one release at least. Maybe warn somewhere that the legacy codes could be removed somewhere in the future.

**Comment by tacaswell** [comment]
I don't see any reason to remove it.  I think this is analogous to keeping the recursive, non-recursive, and numba linking methods around (and we should add a version based on the Hungarian optimization algorithm).

Most users will only use the default, but if people want to dig down and try a different one (because _their_ science is a special snowflake) it is available.

**Comment by caspervdw** [comment]
Is anybody working on the implementation of this? I am willing to invest some time to write a bandpass based on `scipy.ndimage` convolution, also to solve the mass and signal normalization issue discussed in #239
