### ISSUE TITLE
Issues with feature characterization

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/trackpy#237]
For making some estimates of static error in anisotropic feature finding, I did some work on the static error estimation. In [this](http://nbviewer.ipython.org/urls/dl.dropboxusercontent.com/u/36853001/Feature%20characterization.ipynb) notebook I tried to make clear that there are some fishy things going on in the feature characterization.

I would like to propose to do all feature characterization on the raw image instead of the preprocessed (rescaled, bandpassed) image. For my 12-bit images the current implementation gives entirely wrong mass estimates.

If we then calculate the static error from the (correctly calculated) mass, and not from the max pixel intensity, the error estimate will be more robust to noise and I will be able to extend it for anisotropic features.

There are still some more things I need to solve, so I will probably update this post in the future.

What are your thoughts on this?

**Comment by danielballan** [comment]
Thanks for investigating and presenting this thoroughly. The "signal" is certainly the most error-prone input to the noise computation, and your new way of calculating epsilon using mass instead of signal is clearly superior.

Do you know whether Savin & Doyle intended "signal" to come from the processed on unprocessed image? I couldn't convince myself either way, but I decided that the max pixel intensity could more accurately be measured with noise removed.

Do you think that rescaling is the whole source of the problem with mass estimates? Could they be due to overflow errors? I am surprised that unprocessed and processed images give such starkly different estimates for mass.

**Comment by nkeim** [comment]
Wow, the current behavior does not look good!

Preprocessing is critical for some experimental images, because various optical errors or artifacts can add a long-wavelength "background" that must be subtracted off. This background would otherwise inflate the signal. Perhaps there is a different way to do the rescaling? Or as @danielballan suggests, maybe there is a bug somewhere.

**Comment by caspervdw** [comment]
The mass is overestimated with a factor 16, so it seems to have something to do with the `scale_to_gamut` preprocessing that rescales my 12-bit image to 16-bit (giving you the factor 16).

I understand that background subtraction is needed, but why the rescaling?

**Comment by danielballan** [comment]
The bandpass returns a float image, which is rounded to an integer dtype for performance reasons. (IIRC, I found that the dilation step in particular was much faster for ints.) Before this rounding takes place, the rescaling fills the gamut to retain as much contrast as possible. For uint8, this makes a difference: more detail is kept. But for higher bit depths, I would guess that is makes little if any difference.

Looking back on it now, I think rescaling is too aggressive. The user should do this themselves if it needs to be done at all. Because, of course, if the min and max values of the images vary significantly over time, the scale by which "mass" is measured will be inconsistent over time.

If removing the rescaling altogether does not hurt the subpixel precision to badly (i.e., if the feature tests still pass) then I think it would be fine to remove it for v0.3.

**Comment by caspervdw** [comment]
If the rescale has this function then I am not directly in favour of removing it. I see the preprocessing as something that only helps the subpx refinement; the characterization should - in my opinion - be about the non-processed image.

So I propose changing 'mass' to just the sum of raw px intensities. `signal` is probably better from the preprocessed image (currently it is taken from the raw image). `size` and `ecc` should be investigated.

I think that Savin & Doyle intended 'signal' to come from the unpreprocessed image; if they explicitly remove the background B in eq. (42), S_tot must be the raw image and not the preprocessed one. Also, they assume that noise averages out over the mask region, that's why in the denominator in there is no dS term: it integrates to zero. By the way, this denominator is the total sum of pixel intensities: no need to deal with `signal` at all, just use a background-corrected `mass`, which is a more robust quantity.

**Comment by danielballan** [comment]
Note to selves: this was partially addressed in #239. Discussion will continue in #260 after the v0.3 release.
