### ISSUE TITLE
Tutorial bugs

### ISSUE THREAD

**Issue by danielballan** [soft-matter/trackpy#247]
- Replace the seaborn import(s) with mpl.style.use, or nothing.
- The uncertainty tutorial is missing a numpy import.

**Comment by nkeim** [comment]
In the walkthrough, `minmass=2000` no longer works. `minmass=200` seems OK.

**Comment by nkeim** [comment]
Near the end of the walkthrough, parallel feature-finding fails for me because "`PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed`"

**Comment by danielballan** [comment]
@nkeim What version of IPython?

**Comment by danielballan** [comment]
@nkeim Re: the minmass change, is this because we are now filtering on raw_mass? Just making sure I understand what happened.

**Comment by caspervdw** [comment]
@nkeim @danielballan All mass results are changed because of the issue discussed in https://github.com/soft-matter/trackpy/issues/237 . The `scale_to_gamut` rescales the (preprocessed) `image` values so that the calculated mass is overestimated. As of https://github.com/soft-matter/trackpy/pull/239 this is counteracted by dividing the masses by the scalefactor.

This must be mentioned in the release notes. The difference can easily be as large as a factor of 16 for 12-bit pictures (which are rescaled to 16-bit, so factor 16)

**Comment by caspervdw** [comment]
Just made a PR to update the 3D tracking: https://github.com/soft-matter/trackpy-examples/pull/26

**Comment by nkeim** [comment]
I figured it was something like that. This is a big, big deal, because it means that *most* code that calls trackpy needs to be edited to give comparable results. It would be as though we switched from diameter to radius — except the conversion is not necessarily straightforward.

How can we explain this in the release notes? We need to explain the reason for this change and show an easy way to convert `minmass`. How about

> trackpy has a new method of calculating feature "mass" that compensates for bit depth and the details of preprocessing. This means that masses are more likely to be consistent under changes in image brightness or format. To obtain results comparable to those from older trackpy versions, you may have to adjust your `minmass` parameter (and other parts of your code that use the mass). A good rule of thumb is…

…is there one?

Also, this really tips the scales for making the release notes required reading for anyone doing an upgrade.

**Comment by danielballan** [comment]
That reads right to me. We always knew that v0.3 would break some things.
This will probably be the most important and potentially confusing change.
But it fixes something about the IDL implementation that always bugged me.

**Comment by caspervdw** [comment]
The scaling factor is provided by `scalefactor_to_gamut`, a good rule of thumb is as follows:

* Calculate the scaling factor:
for <8-bit integer or float images: 255 / (maximum intensity in image)
for <16-bit integer images: 65535 / (maximum intensity in image)

* Divide minmass by that factor.

I guess we can write an `minmass_old_to_new` convenience function. What about that?

**Comment by danielballan** [comment]
I like that plan. It's a simple enough function, but there's no reason not to be as friendly as possible.

**Comment by caspervdw** [comment]
I can look into the walkthrough tomorrow.

**Comment by ghattab** [comment]
I tested the reproducibility between trackpy v0.2.4 and v0.3.0rc1 on the same dataset.
This line 
f0 = tp.locate(frames[0], diameter=11, invert=True, minmass=8000)

**Comment by tacaswell** [comment]
@ghattab Can you make that it's own issue?

**Comment by caspervdw** [comment]
That is strange. The minmass has certainly changed in v0.3, but it should be lower in magnitude in v0.3.
Can you provide a single frame from your dataset?

I am working on a `minmass_version_change` convenience function, I will push this as soon as I tested it.
