### ISSUE TITLE
More modular feature finding

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/trackpy#257]
As discussed in #239 and recently in #244, I would like to open a discussion on making feature finding more modular and hopefully more flexible and readable. I had a look at the code and we could breakdown locate in the following steps:

```
<parameter checks>
invert(raw_image)  # I would prefer to put this in a process_func and remove it from locate
image = preprocess(raw_image, noise_size, smoothing_size, threshold)
coords = local_maxima(image, radius, percentile, margin)
filter(coords, minmass, maxsize)
refine(raw_image, coords, separation, max_iterations, engine)  #possibly with characterize
filter(coords, minmass, minsize, topn)
characterize(raw_image, image, coords, radius, threshold)
```

To make the API user-friendly, we can work with `function`, `_function` combinations respectively including and not including the parameter checks.

I wonder what the performance loss would be if we would remove characterization from `refine` and write a new (possible numba) `characterize`.

What is the best place to make the transition `ndarray` -> `DataFrame`?

**Comment by danielballan** [comment]
I think this is a good direction. Some quick thoughts:

1. I want `locate` to stick around in some form. It's good for new users with simple tasks.
2. But I think `batch` should be retired, in favor of a for loop. We don't have to remove it from the package, but we shouldn't use it in our examples.
3. I agree that `invert` should be removed from `locate`.

In my opinion, lowest-level API should favor numpy arrays. Converting *back* from a DataFrame to numpy array (`.values`) unfortunately copies data. And the column labels don't add much utility until you get to `characterize` anyway. Depending on how others feel, I'd suggest either (1) all low-level functions return numpy arrays or (2) `characterize` returns a DF, but nothing else does.

**Comment by tacaswell** [comment]
I am ambivalent to 1. heartily agree with 2. and 3. 

I strongly agree with (1) and grudgingly accept (2).

**Comment by nkeim** [comment]
I'm in favor of `locate` staying around. The main reason is that so many parameters are length scales that go as `diameter`. The secondary reason is that we are lucky that for many users, our core API is 2 functions. That makes trackpy super easy to get started with, as @danielballan says.

If we're considering deprecating or dropping parts of the API, what about cutting the number of parameters for `locate()`? For example, `characterize` could always be False, and `engine` could always be `auto`. There are several other parameters like this. This would break some backward compatibility, but it would clearly identify `locate()` as the "beginner mode" function. There would be a tutorial that would reveal the code snippet in the original post, explain what each step does, and show how to alter or tune its behavior.

As for using numpy arrays instead of DataFrames: I think `refine()` needs to return a DataFrame. This is mostly because not everyone will want to run `characterize()`, and `make_features_df()` is just weird.

**Comment by nkeim** [comment]
Also, to be clear, we're talking about v0.4 at the earliest, right? :grimacing:

**Comment by danielballan** [comment]
Haha, yes, we really do need to declare feature freeze on 0.3. I have no
problem tagging 0.4 on its heels if we have some momentum.

**Comment by caspervdw** [comment]
In view of upcoming api changes in locate, what about adding deprecation warnings for 'invert', 'engine' and 'characterize' to v0.3 already?

For the invert we could redirect users to an equivalent pims pipeline. (Which raises the issue on adding example pipelines to pims)

**Comment by nkeim** [comment]
I think this might belong in v0.3.2 (assuming 0.3.1 is a bugfix). I'm still not convinced we know the best "fix" for these parts of the API that are mostly just inelegant. I'm hesitant to start warning users that they're "doing it wrong" before we can confidently tell them how to do it right.

Better to introduce the new API in 0.3.2 or 0.4 alongside the old one, then remove the old one in the following major release.

On Sep 5, 2015, at 11:44 AM, Casper van der Wel <notifications@github.com<mailto:notifications@github.com>> wrote:


In view of upcoming api changes in locate, what about adding deprecation warnings for 'invert', 'engine' and 'characterize' to v0.3 already?

For the invert we could redirect users to an equivalent pims pipeline. (Which raises the issue on adding example pipelines to pims)

-

**Comment by caspervdw** [comment]
What about the following submodules:

- `trackpy.find` for `local_maxima` - like routines
- `trackpy.refine` for `refine`
- `trackpy.preprocess`
- `trackpy.locate` for all convenience routines that combine `find` and `refine`
- `trackpy.feature` (?) for `characterize` and `filter`-like functions

**Comment by nkeim** [comment]
I think we should keep `feature` as the module for convenience routines. I think we can do this with minimal API breakage, maybe just dropping some lesser-used keyword args from `locate` and `batch`. And I think that the characterizing and filtering functions may be sufficiently high-level that they can also be included in `feature`.

I am starting to think of this as a "deli menu" approach for ordering sandwiches. We provide our customers with premade sandwiches ready to go (a simplified version of `locate`), as well as some suggested recipes (in the documentation, e.g. for dense or sparse features, or for maximum performance). But then they can also come behind the counter to make the sandwich themselves, perhaps even using their own ingredients.

However, we are also starting to see the downside into composing functions into a custom tracking pipeline: individual functions will be given just enough parameters to work, but they will not know enough about the rest of the pipeline to have sensible defaults or warn about inappropriate values. Instead of letting the user tweak individual pieces of the pipeline, she must take responsibility for the entire thing all at once. We are seeing this in #355  — `locate()` behaves differently than composing individual functions, because it knows more and tries to do the right thing. As we simplify and break up the pipeline (which I'm in favor of!), we are going to see more of that, not less.

**Comment by tacaswell** [comment]
I like the deli analogy.

If the pre made pipelines do some high level cleanup, that logic should
also be pulled out in to helper functions as well.

**Comment by caspervdw** [comment]
This sounds like a good idea to me! I like the analogy.

To suppress unexpected results (@nkeim ) we should be very specific and picky about the parameters given to any of the 'custom' functions. `locate` can on the other hand be more accomodating: we could even convert images to gray by default if necessary, etc.

We should begin by dissecting `locate` into manageable functions. If we can do that while keeping the tests (so the API of locate) intact, that would be a great first step.

**Comment by danielballan** [comment]
Agreed all around. I will definitely be stealing that deli analogy. I think trackpy is at the point where we should try avoid breaking the `locate` API if possible.

**Comment by nkeim** [comment]
I think @caspervdw describes the right approach with `locate()`. Another way to put it is as a challenge: can we take the core part of the `locate()` source code and, for a typical use case, make it so short that we can give it as an example in the documentation?
