### ISSUE TITLE
Linking performance issue

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/trackpy#280]
With a colleague I had the following issue:

    z = f[(f.x > 860) & (f.x < 960) & (f.y > 609) & (f.y < 690) & (f.frame < 100)].copy()
    %timeit tp.link_df(z, search_range=10, memory=1) 
    Frame 99: 3 trajectories present
    1 loops, best of 3: 537 ms per loop

    z = f[(f.x > 860) & (f.x < 960) & (f.y > 609) & (f.y < 690) & (f.frame < 100)]
    %timeit tp.link_df(z, search_range=10, memory=1) 
    Frame 99: 3 trajectories present
    1 loops, best of 3: 30.7 s per loop

So much lower performance when linking a view. Is this a known issue @nkeim? Can we give some kind of warning if this case arises?

By the way, we are using 0.3.0rc1

**Comment by nkeim** [comment]
Fascinating!! Will try to reproduce so I can profile it. Maybe we're just using pandas wrong.

On Sep 10, 2015, at 5:58 AM, Casper van der Wel <notifications@github.com<mailto:notifications@github.com>> wrote:


With a colleague I had the following issue:

z = f[(f.x > 860) & (f.x < 960) & (f.y > 609) & (f.y < 690) & (f.frame < 100)].copy()
%timeit tp.link_df(z, search_range=10, memory=1)
Frame 99: 3 trajectories present
1 loops, best of 3: 537 ms per loop

z = f[(f.x > 860) & (f.x < 960) & (f.y > 609) & (f.y < 690) & (f.frame < 100)]
%timeit tp.link_df(z, search_range=10, memory=1)
Frame 99: 3 trajectories present
1 loops, best of 3: 30.7 s per loop


So much lower performance when linking a view. Is this a known issue @nkeim<https://github.com/nkeim>? Can we give some kind of warning if this case arises?

**Comment by caspervdw** [comment]
We might need to do something with `f.is_copy`, if that returns `None`, the dataframe is a copy and not a view.

**Comment by nkeim** [comment]
I took the walkthrough notebook, restricted feature-finding to the first 100 frames, and then ran

`%prun t = tp.link_df(f[f.frame > 0], 5, memory=3)`

and

`%prun t = tp.link_df(f[f.frame > 0].copy(), 5, memory=3)`

There was a large timing difference, though not as dramatic as what you report. It appears to be entirely due to `gc.collect` going crazy when the input is a view:

```
      1410725 function calls (1404209 primitive calls) in 7.032 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      101    5.213    0.052    5.213    0.052 {gc.collect}
      100    0.237    0.002    1.174    0.012 linking.py:926(link)
       98    0.116    0.001    0.291    0.003 linking.py:1182(assign_candidates)
       98    0.102    0.001    0.153    0.002 linking.py:1069(_assign_links)
52205/52006    0.102    0.000    0.104    0.000 {numpy.core.multiarray.array}
      199    0.073    0.000    0.073    0.000 {method 'get_indexer' of 'pandas.index.IndexEngine' objects}
       98    0.069    0.001    0.073    0.001 {method 'query' of 'scipy.spatial.ckdtree.cKDTree' objects}
```

Our linking code must be inadvertently creating some monstrous abomination of a data structure when it is passed a view. Additionally, I got the usual setting-on-a-copy warning from Pandas.

I do not want to wade deep into the Pandas arcana to fix what seems like an issue that affects very few use cases. So I am all for the warning you suggest. The warning can recommend using the `copy_features` kwarg, which appears to fix the problem.

I can make the PR but I don't know if I can do it in time for v0.3.0.

**Comment by caspervdw** [comment]
I made the PR, closing
