### ISSUE TITLE
trackpy.batch 19 parameters in method signature, 11 documented on web page

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#305]
A few parameters of batch appear to be missing on the web page. The 8 missing parameter descriptions appear in the feature.py source in batch::"Other Parameters", should these be included on the html page?

http://soft-matter.github.io/trackpy/generated/trackpy.batch.html#trackpy.batch

**Comment by tacaswell** [comment]
It looks like something is going sideways with the numpydoc parsing or the sphinx template.

**Comment by nkeim** [comment]
numpydoc doesn't render the "Other Parameters" section, period. This includes the latest development branch. This is a quasi-documented behavior and is not necessarily a bug: http://numpy-discussion.10968.n7.nabble.com/numpydoc-quot-Other-Parameters-quot-section-td26504.html

Is this section rendered in the matplotlib docs? If so we should just borrow some code.

Otherwise, we should just move everything to the "Parameters" section and move on.

**Comment by danielballan** [comment]
Switching to neopolitan may help. Have not tried this.

**Comment by nkeim** [comment]
For future reference, this is: http://sphinx-doc.org/latest/ext/napoleon.html

On Nov 9, 2015, at 7:04 PM, Dan Allan <notifications@github.com<mailto:notifications@github.com>> wrote:

Switching to neopolitan may help. Have not tried this.

**Comment by caspervdw** [comment]
I am in favor of merging Parameters and Other Parameters. The distinction is a bit arbitrary anyway.

**Comment by danielballan** [comment]
That's OK with me. I picked up the pattern from scikit-image, I think, but it has downsides.
