### ISSUE TITLE
Faster MSD calculations

### ISSUE THREAD

**Issue by hadim** [soft-matter/trackpy#335]
I found a Python implementation to compute MSD with FFT which seems faster than conventional MSD algorithm because the algorithm is `O(N*log(N))`.

I did a quick and small benchmark here : https://github.com/hadim/public_notebooks/blob/master/quick_msd_calculations/quick_msd_calculations.ipynb

Two things : 

- the returned `DataFrame` is less detailled than in `tp.msd`.

- the msd array is sliced at the end of the function to take into account `max_lagtime` parameter which is really not efficient ! I didn't find a way to integrate it in the algorithm and I don't know wether it's possible.

Would you be interested by a PR to integrate it into trackpy ?

If you do, we also need to discuss how to inegrate it with `tp.imsd` (maybe with a `fft=False` default parameter ?).

Edit : I added `max_lagtime` into the loop. According to the author of the algorithm it's not possible do things faster with `max_lagtime`.

**Comment by danielballan** [comment]
Interesting. That's a big speedup!

Yes, I'd be very interested in seeing this as a PR into trackpy. Since it has different advantages and limitations compared to the existing implementation, I'm guessing it will make the most sense to incorporate as a separate function that either replaces or sits alongside the existing one (rather than implementing a keyword argument to switch between them).

If it is not possible to compute the extra "detail" columns using the FFT implementation, perhaps we could make `detailed_emsd` (current implementation, `detail=True`) and `emsd` (FFT implementation).

In addition, I think the existing `emsd`/`imsd`' could be vectorized more effectively. I'll look at this in a separate issue/PR.

**Comment by hadim** [comment]
I created a `msd_fft` function. For `emsd` and `imsd` I think it's cleaner to add a paramter `fft` to avoid code duplication.

What do you think ?

If you don't like it, tell me how should I duplicate the function please : `emsd`/`emsd_fft` and  `imsd`/`imsd_fft`

**Comment by danielballan** [comment]
Any thoughts from the rest of the team of this?

**Comment by hadim** [comment]
I'll make the PR the way I think it's fine and then we can discuss there and iterate to modify the API.

**Comment by danielballan** [comment]
Great. Thanks a lot for looking at this!

**Comment by hadim** [comment]
Discussion continue to #337
