### ISSUE TITLE
Help needed for making GUI for trackpy

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#427]
I have been playing with tkinter in the hope of making a GUI for trackpy similar to PolyParticleTracker.  

It would be a huge help if someone could tell me how I can display (or embed) the various plots that trackpy generates (shown in the walkthrough) within a tkinter window.

Some of the plots appear to be stored as numpy arrays, but others are different enough to make me think that embedding the results of tp.annotate etc. may be better achieved thru directly embedding matplotlib plots into tkinter.

Thanks in advance.

**Comment by caspervdw** [comment]
Hi @Resonanz, great that you are working on a GUI for trackpy! That would be a nice addition.

I have some work on a viewer for PIMS, based on the skimage viewer. It contains an Axes object on which you can plot anything using for example `tp.annotate(..., ax=viewer_axes)`. So you can provide most of the trackpy plotting functions a custom `ax` on which it will plot.

I hope this helps. I will make a repo for my pimsviewer. Maybe we can bundle our work into a nice GUI for trackpy.

**Comment by pfigliozzi** [comment]
Hi @Resonanz,

I have been using trackpy recently for research and I have also been finding a need to have a GUI like interface to help with particle tracking. Right now, my needs were met by finding an easy way to flip through frames of trackpy identified features or trackpy tracked trajectories. The pims library used in the trackpy tutorial uses scikit-image and I found in there a nice image viewer that can be extended for this purpose. It can be extended with a number of plugins to quite easily create a custom GUI around a simple image viewer similar to ImageJ. See the [ImageViewer api entry](http://scikit-image.org/docs/stable/api/skimage.viewer.html#imageviewer) for more information but the api reference for the [Plugin class](http://scikit-image.org/docs/stable/api/skimage.viewer.plugins.html#plugin) and the docstring on [CollectionViewer](https://github.com/scikit-image/scikit-image/blob/master/skimage/viewer/viewers/core.py#L324) really helped me create exactly what I wanted.

To help you out I can post the code I made that allows you to use the image viewer as a replacement for `tp.annotate`. This was done by sub-classing the `CollectionViewer` class and creating a my own `__init__` method and replacing the `update_image` method. Here is the class that I wrote that does the annotation in the ImageViewer:
```python
from skimage.viewer import CollectionViewer
from skimage.draw import circle_perimeter
from matplotlib.patches import Circle
from matplotlib.collections import PatchCollection
import numpy as np
import pims
import glob

class ParticlePositionViewer(CollectionViewer):
    """A subclass of the skimage viewer that will display
    the position of particles on the images in a pims 
    object.

    Parameters
    ----------
    image_collection : ND image collection
        
    df_positions : DataFrame
        needs to contain columns ['frame', 'x',
        'y'].
    """
    def __init__(self, image_collection, df_positions, pos_columns=['x','y']):
        CollectionViewer.__init__(self, image_collection)
        self.df_positions = df_positions
        self.artists = None
        self.circle_kwargs = dict(edgecolor='r', radius=6, facecolor=None, fill=False, lw=1)
        
        self.pos_columns = pos_columns

        image = self.image_collection[0]
        
        # Use the min/max of the first image for all other images
        self.vmin_vmax = (np.min(image), np.max(image))
        
        self.update_image(image)
        
        
        
    def update_image(self, image):
        """Update displayed image.
        This method was overwritten in the skimage viewer. This method will
        plot the particle positions on the image.
        """
        if self.artists != None:
            self.artists.remove()
        image_df = self.df_positions[self.df_positions['frame']==self.index]

        # Add the circles over each particle
        patches = [Circle((v[self.pos_columns[0]], v[self.pos_columns[1]]), **self.circle_kwargs) for idx,v in image_df.iterrows()]
        collection = PatchCollection(patches, color='r', facecolor='none')
        self.artists = self.ax.add_collection(collection)
        
        
        self._update_original_image(image)
        self._image_plot.set_clim(self.vmin_vmax)
```

If you have a `DataFrame` of identified features from trackpy and you already have a `pims.ImageSequence` object, you can call the image viewer using a function similar to `tp.annotate` like the one below:
```python
def annotate(df_positions, pims_obj):
    """Function to display the localized positon of particles in
    an image viewer.
    """
    viewer = ParticlePositionViewer(pims_obj, df_positions)
    viewer.show()
```

I have also made a sub-classed `CollectionViewer` to make a way to flip through my frames and show the trajectories of my particles using color tails to show the last, e.g. 3, frames of the particle's location on each frame. Let me know if you are interested in that as well.

I am not saying that an entire GUI for trackpy should be written by sub-classing scikit-image, but the `CollectionViewer` provides a very good base for handling an image stack and can be extended. It may even be used as part of a GUI where a tkinter window controls parameters.

However, to answer your original question about embedding matplotlib in tkinter you can look at an example in the [matplotlib documentation](http://matplotlib.org/examples/user_interfaces/embedding_in_tk.html) for an example.

Coincidentally, I have been meaning to talk to @nkeim (and maybe also @caspervdw who responded with a similar answer while I was typing this one) about adding some of my code to the repository. The way I have things written may not work well for everyone as for loops are used to draw objects which would probably get quite slow for users with lots of particles.

**Comment by caspervdw** [comment]
@pfigliozzi It seems like we were working on the same lines! I am very much in favor of giving this an own repo under soft-matter. 

Basing this on the `ImageViewer` would be a good idea. I think we will need a `PimsViewer` class that exposes an easy to understand `Plugin` framework. I have written something like that a year ago. Although still unfinished, I will push that to my own repo soon. It will need to be rebased on skimage because I copied and adapted their viewer code base.

**Comment by caspervdw** [comment]
And @pfigliozzi would be great if you share your work on this!

**Comment by nkeim** [comment]
This would be great! I agree that having a simple way to view results—ideally one that requires no new dependencies—would be welcome by many trackpy users.

I have had a lot of success with interactive IPython widgets for tuning feature-finding. These have the advantage of not constraining you to a specific set of diagnostic plots, or a specific workflow. They also let you introduce custom pre-processing and other weird stuff (which I use). So I think that a GUI for viewing results and diagnosing problems should be usable independently from a GUI for setting parameters—which seems to be the easiest course, anyhow.

@pfigliozzi if your *vision* is for a lightweight subclass like you described, it might be nice to have this in trackpy as a "batteries included" feature. Otherwise it can go in a separate repo, and conda and Travis can help us keep them integrated.

**Comment by Resonanz** [comment]
Guys, thanks for the feedback.  Upfront I would say that you all know a lot more about python coding than I do, but I did manage to get Github working tonight on my desktop PC and uploaded the files I have been working on (this should work if you clone it and run "python trackpyGUI.py"):

https://github.com/Resonanz/trackpyGUI.git

The code is very basic.  It creates a single tkinter frame in which everything is to be displayed. Currently I put the cursor in the PATH box and press ENTER and it (dis)confirms the path validity. Ditto for the file extension (the files in the repo are .tif files).  If valid, if reads the 81 video frames and displays basic info. The arrow keys take you to the first and last frames, and one frame at a time in each direction. "PIMS read frames displays "frames[0]" and then runs some Walkthrough code.

So, all that said, I would just like the s/w to do the very basics -- read the frames via a GUI, and give me some animated frame-by-frame tracking (with red circles) and some other plots shown in the Walkthrough, and finally the diffusion coefficient and slope of the log-log MSD-vs-LagTime plot.

PolyParticleTracker does basically what I have described above AFAICT. So what do you guys think?  I am open to ideas.

**Comment by caspervdw** [comment]
I will have a look into your repo @Resonanz, thanks.

My code is on https://github.com/caspervdw/pimsviewer

It reimplements the `skimage.viewer.CollectionViewer` for N-dimensional frames, including the `Plugin` infrastructure that @pfigliozzi also mentioned.

**Comment by pfigliozzi** [comment]
@nkeim I was originally thinking of just adding my tool to the trackpy library as a way for users to view particle positions or trajectories. The problem with the code that I wrote is I don't think it is general enough and only works for 2D image stacks like the ones I work with. It may still be worth adding though.

However, I think @caspervdw's pimsviewer would be a good alternative to use instead of the skimage viewer as it appears to support NDimensional image data out of the box, something that the skimage viewer does not do.

Anyway, you can check out the classes I wrote using the skimage viewer here https://github.com/pfigliozzi/Python_Data_Analysis/blob/master/trackpy_helper_functions.py
It is just two classes where one does the annotation and one displays the trajectories. Then there are four functions to easily call the viewers (either a pims object from memory or to call the images from a path).

**Comment by caspervdw** [comment]
I have updated the pimsviewer repo https://github.com/caspervdw/pimsviewer, cleaned a bit and added some examples.

@pfigliozzi  I agree that my pimsviewer would be best to use as a basic infrastructure, on which we can build "plugins" to provide extra functionalities such as annotation. Annotate plugin appears to be very similar to mine. But the Trajectory plugin would be a great addition.

@nkeim @tacaswell @danielballan  Are you :+1: of starting a "pimsviewer" repo on soft-matter?

@pfigliozzi @Resonanz Would you be willing to maintain that repository together with me (and possibly others)?

Any suggestions for a better name than "pimsviewer"?

**Comment by Resonanz** [comment]
trackpyGUI ?

**Comment by danielballan** [comment]
Yeah, I'm enthusiastically :+1: on pimsviewer as a soft-matter repo. We will definitely use this at BNL.

@Resonanz I think it's useful to maintain trackpyGUI as a separate project from pimsviewer because pimsviewer is useful beyond the scope of particle tracking. I'm excited that you're working on this!

**Comment by nkeim** [comment]
👍 on @danielballan's comment: trackpyGUI and pimsviewer will both be extremely useful, but it makes the most sense for them to be separate projects.

**Comment by tacaswell** [comment]
https://github.com/tacaswell/leidenfrost/tree/master/leidenfrost/gui is GUI code I wrote around trackpy for my grad work (sorry, it is a bit scary in there), but some maybe useful widgets in https://github.com/tacaswell/leidenfrost/blob/master/leidenfrost/gui/common.py

there is a project called guidata https://pythonhosted.org/guidata/ which gives a declarative way of making Qt guis.

There is discussion going on at  https://github.com/matplotlib/matplotlib/issues/1543 on a very similar vein.

**Comment by Resonanz** [comment]
@caspervdw Yes, keen to be a part of the team... looking at pimsviewer now...

**Comment by Resonanz** [comment]
For reference, here is a photo of PolyParticleTracker's one and only screen.  My desire for trackpyGUI is to follow along the same lines but to have a range of plots used in the WalkThrough shown inside the window. I want to be able to easily load the series of images, tune the detection algorithms, and ultimately obtain the MSD, van Hove, etc data, and export the plots using MatPlotLib.

![wp_20170228_08_24_53_pro](https://cloud.githubusercontent.com/assets/6218191/23376452/f9e388fa-fd90-11e6-8b99-a4b9619a42d0.jpg)

**Comment by caspervdw** [comment]
Closing through https://github.com/soft-matter/pimsviewer/issues/3
