### ISSUE TITLE
linking.py, acquiring the number of levels

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#443]
I'm wondering what the fastest approach is to acquiring the number of levels is in linking.py:link_df_iter ?
One approach is to pass in df.frame.nunique() to link_df_iter which works.

**Comment by nkeim** [comment]
I'm a little unsure of the context. Do you want to know the number of levels *before* or *after* linking? Since you are using `link_df_iter`, are you streaming from disk?

**Comment by apiszcz** [comment]
Before linking.

**Comment by nkeim** [comment]
I'm still not quite sure of the context, but usually I would just use `len()` with whatever iterable that you are getting the features from, whether it is a `PandasHDFStore` or `pims` reader object or whatever. There is no generic way, because generically you cannot get the length of an iterable without looping over all the items, but many of these objects nonetheless support `len()`.

`df.frame.nunique()` would work if your data were in a single DataFrame, in which case you would be using `link_df()` and not `link_df_iter()`, so I am confused about that as well.
