### ISSUE TITLE
pixel number sensitivity in walkthrough 

### ISSUE THREAD

**Issue by Zhhjll** [soft-matter/trackpy#456]
Hi all,

I am trying to use the walkthrough example, for the exact same conditions as mentioned in the walkthrough example. I want to measure the diffusion coefficient of 5um particles but I realize the measurement procedure is very sensitive to the pixel number and the micron to pixel ratio and also frame rate. According to the walkthrough, the particles are 1 micron and it is estimated as 11 pixels, is it the diameter of the particle in pixel? on the other hand, the ratio of micron/pixel is 100/285? I was wondering what is the correlation between the 100/285 micron/pixel ratio and the 11 pixels for 1 micron? also, I have a question about the mass of particles? How has it been calculated? if the 1micron has mass=400 I get mass=55000 much greater! Can anybody help me explain these discrepancies?

Thank you!

**Comment by charlesreid1** [comment]
I might be able to help answer your question about the discrepancy in mass values (but I agree the question about the microns-per-pixel value are important and remain unresolved).

# Mass Values

If we generate two "fake" particles, one black dot on a white background and one dark gray dot on a light gray background, we see that the mass values differ between them. For example:

**black_and_white.png:**

![black-particle-white-background](https://i.imgur.com/fM0g979.png)

**gray_and_gray.png:**

![gray-particle-gray-background](https://i.imgur.com/zholKtF.png)

Now, if we run the following sample program:

```
import pims
import trackpy

frames1 = pims.ImageSequence('black_and_white.png', as_grey=True)
frames2 = pims.ImageSequence('gray_and_gray.png', as_grey=True)

f1 = trackpy.locate(frames1, 25, invert=True)
f2 = trackpy.locate(frames2, 25, invert=True)

print("="*20)
print("black on white:")
print(f1[['mass']])

print("="*20)
print("gray on gray:")
print(f2[['mass']])
```

we can see that the case of black-on-white gives larger values for the mass (brightness) than the gray-on-gray case:

```
====================
black on white:
           mass
0  16607.503577
====================
gray on gray:
          mass
0  7600.111472
```

The black-and-white case has nearly twice the mass as the gray-and-gray case. So, the differences in mass are likely due to your PIV images having a higher contrast (looking more black-on-white than gray-on-gray) than the walkthrough's [sample images](https://github.com/soft-matter/trackpy-examples/blob/master/sample_data/bulk_water/bulk_water_000.png), which are pretty close to gray-on-gray.

# Microns Per Pixel Value

@Zhhjll raises an excellent question about the micron-per-pixel value used in the walkthroughs; the value used for computing the mean squared displacement is 100/285 = 0.35, while the apparent size of the 1 micron particles is about 6 pixels (see screenshots below), for a value of 0.1667. Yet another value for the particle diameter is used for feature-finding, of 11 pixels per particle, corresponding to a value of 1 micron per 11 pixels, or 0.090909. There seems to be some inconsistency here.

What makes this an important question is the resulting A and D values that are obtained are very sensitive to the value of microns-per-pixel and to the particle diameter value used. Would it be possible for the developers to shed some light on the values used, and the justification?

![microns-per-pixel1](https://i.imgur.com/OWbMnnt.png)

![microns-per-pixel2](https://i.imgur.com/QomM7DU.png)

**Comment by caspervdw** [comment]
I can comment on the microns-per-pixel issue. Firstly, this value is irrelevant from a feature-finding perspective; trackpy feature finding works exclusively on pixels. To make some physical sense of your data afterwards, of course you will have to convert pixels to mictons. There is a convenience parameter in for instance ‘tp.emsd’ that does this for you.

For these very small features, we have to take into account that the diffraction pattern observed by a microscope is significantly larger than the actual feature size. That is why the features appear to be too large in this example. Typically, you cannot use a diffraction pattern on a bright field image to directly measure the real size of the particles. We have to work with an ‘apparent diameter’.

Then, for feature finding, the quantity ‘diameter’ defines the size of the round mask that is used to cut out the feature from the image to perform subpixel refinement (and other characterizations such as mass computation). Because of this, the value of diameter should be even larger than the apparent diameter: every feature needs to ‘fit’ inside the mask. I agree that we could have chosen this value lower in the example. However, making the diameter too large does not have an enourmous effect (too small on the other hand, has).

So we have: real size, apparent size, and mask size. I hope this makes some sense.

**Comment by danielballan** [comment]
@Zhhjll I'm going to close this issue, but please reopen it if additional clarification would be helpful. This was a good question.
