### ISSUE TITLE
d = tp.compute_drift(t1)  error

### ISSUE THREAD

**Issue by Electronicshelf** [soft-matter/trackpy#462]
Tried this line of code ====>>>  d = tp.compute_drift(t1) 
And i got the error below Please Help...Thanks

TypeErrorTraceback (most recent call last)
<ipython-input-104-f39f73e3be88> in <module>()
----> 1 d = tp.compute_drift(t1)

C:\Program Files\Anaconda2\lib\site-packages\trackpy\motion.pyc in compute_drift(traj, smoothing, pos_columns)
    265     del delta['frame']
    266     delta.reset_index('particle', drop=True, inplace=True)
--> 267     delta.reset_index('frame', drop=False, inplace=True)
    268     dx = delta.groupby('frame').mean()
    269     if smoothing > 0:

C:\Program Files\Anaconda2\lib\site-packages\pandas\core\frame.pyc in reset_index(self, level, drop, inplace, col_level, col_fill)
   3053                 # to ndarray and maybe infer different dtype
   3054                 level_values = _maybe_casted_values(lev, lab)
-> 3055                 if level is None or i in level:
   3056                     new_obj.insert(0, name, level_values)
   3057 

TypeError: coercing to Unicode: need string or buffer, int found

t1.head() Output

          x                  y          mass              size           ecc            signal      raw_mass    ep       frame  particle
295.169679 | 5.570003 | 370.325257 | 2.603612 | 0.173248 | 17.881905 | 10747.0 | 0.085104 | 0 | 0.0
295.360118 | 5.316313 | 388.202575 | 2.524643 | 0.214783 | 18.883275 | 10786.0 | 0.078429 | 1 | 0.0
296.328125 | 5.666915 | 409.267732 | 2.705631 | 0.211014 | 17.458842 | 10758.0 | 0.081641 | 2 | 0.0
296.086566 | 5.877483 | 427.689835 | 2.762346 | 0.220173 | 18.511646 | 10795.0 | 0.075062 | 3 | 0.0
296.030423 | 5.831746 | 408.020517 | 2.700627 | 0.237672 | 18.458071 | 10778.0 | 0.077550 | 4 | 0.0

@tacaswell @sciunto

**Comment by charlesreid1** [comment]
The following line makes it look like this error is occurring from a Conda-installed Pandas:

```
C:\Program Files\Anaconda2\lib\site-packages\pandas\core\frame.pyc in reset_index(self, level, drop, inplace, col_level, col_fill)
```

Can you include the output of the following commands (run from the same Python you're running your trackpy script from) to help shed some light on the issue?

```
>>> import pandas; print(pandas.__version__)
>>> import trackpy; print(trackpy.__version__)
```

**Comment by Electronicshelf** [comment]
Here you go Boss

OUTPUT
import pandas; print(pandas.__version__)    
>> 0.20.1

 import trackpy; print(trackpy.__version__)
>> 0.3.2

**Comment by charlesreid1** [comment]
I did a bit of digging and here's what I found.

The error you're seeing is happening from the `compute_drift()` function in `motion.py`. This function calculates the difference in position, delta x/delta y, between frames for a given particle. However, there's some clean-up that has to happen, since the x and y columns now hold delta x and delta y, but the frame and particle columns hold delta frame and delta particle. So, the original frame number and particle number has to be restored. That's what `reset_index()` is doing when it crashes. 

This error happens when Python expects a string but sees an integer instead (for example, trying to add a string and an integer). It happens [here in v 0.20.1](https://github.com/pandas-dev/pandas/blob/e346c663cf76186c22f4d3b703461b1b60db280f/pandas/core/frame.py#L3055) in the pandas source. That line checks if an integer i is in a string label. **This is likely a bug in pandas**. If you look at the source for the current version of pandas, v 0.21.0, the equivalent location [no longer has that check](https://github.com/pandas-dev/pandas/blob/81372093f1fdc0c07e4b45ba0f47b0360fabd405/pandas/core/frame.py#L3377). Try updating your pandas to version 0.21 and see if that fixes the issue.

If upgrading pandas does not fix the issue, please post the full code that you're using to generate `t1` and that causes the crash. If it's long, or if it requires external data, you can always use a [Gist](https://gist.github.com/) and include a link to the Gist.

Interestingly, the `compute_drift()` method trackpy versions 0.3.2 and 0.3.3 both call the `reset_index()` function, but the current master branch has re-factored the way this is done. [Here is the method compute_drift() in version 0.3.2](https://github.com/soft-matter/trackpy/blob/c309b83296c720b8b9fd9633259c2b9ea6740eeb/trackpy/motion.py#L257-L272), and [here is the method compute_drift() in the master branch](https://github.com/soft-matter/trackpy/blob/master/trackpy/motion.py#L263-L281) for comparison. So, another option to try and fix this would be to update your trackpy by building it from the master branch. (I've noticed a substantial increase in speed using the numba engine by building from the trackpy master branch, compared with the version of trackpy available through pip, so this may be worth trying anyway.)

For the record, [here](https://github.com/soft-matter/trackpy/commit/8590a6d8b4f21ed1fdc33183435334fb202ae1ee#diff-d63608fc47e191876c0f7677b166f389) is the commit where the `reset_index()` function calls were introduced to `compute_drift()` (Feb 2016).

**Comment by Electronicshelf** [comment]
Thanks a million for the help, i just decided to reinstall the whole package from scratch after reading your comments. Everything seems okay now!!

**Comment by nkeim** [comment]
Thanks, @charlesreid1 ! I think this underscores how we really need to release v0.4 (#441) soon. I will have some time to contribute in December, possibly sooner.
