### ISSUE TITLE
Use additional information to resolve tracks?

### ISSUE THREAD

**Issue by nodice73** [soft-matter/trackpy#470]
Hello,

I find trackpy to be intuitive and a pleasure to use. Thank you for making a great module!

I was wondering if there was a way to include more information than position to help the algorithm resolve close particles. For example, I have cell data which includes e.g., their area, fluorescence intensity, etc. I've noticed mistakes in high-density areas that would be easily resolved if there was some concept of weighting potential links by the value(s) of some other parameter(s).

I'm guessing this would be similar to how velocity prediction is implemented.

Thanks again!

**Comment by nkeim** [comment]
Hi! Thanks for using trackpy! I’m not quite sure what you mean, but since trackpy supports n-dimensional tracking, you can use quantities like intensity or size to assist linking. You just add it to the list you specify with pos_columns. You usually need to rescale the quantity so that differences in size values (for example) are comparable to distances in space; you may also need to increase search_range. I have done this before with some success.

On Jan 10, 2018, 6:06 PM -0800, Adam Waite <notifications@github.com>, wrote:

Hello,

I find trackpy to be intuitive and a pleasure to use. Thank you for making a great module!

I was wondering if there was a way to include more information than position to help the algorithm resolve close particles. For example, I have cell data which includes e.g., their area, fluorescence intensity, etc. I've noticed mistakes in high-density areas that would be easily resolved if there was some concept of weighting potential links by the value(s) of some other parameter(s).

I'm guessing this would be similar to how velocity prediction is implemented.

Thanks again!

**Comment by nodice73** [comment]
Yes, this is exactly what I was talking about.

You might want to mention this explicitly in the docs, as I was being too literal about the meaning of 'pos_columns'.

Thanks again!
