### ISSUE TITLE
BUG: Particle added to track twice

### ISSUE THREAD

**Issue by nkeim** [soft-matter/trackpy#472]
I tried out the master branch for my regular analysis workflow. I got as far as running linking on some of my smaller movies, in this case ~54k particles for 19200 frames. It looks like they were failing because of an exception in `linking.utils.Point.add_to_track`: `trying to add a particle already in a track`. This occurred at some arbitrary point in each movie, after hundreds of frames.

This was regular linking, not `find_link`. Prediction and `adaptive_step` were in use. The data are generally messy and are no doubt a good place to find edge cases. Linking works fine with the v0.3 implementation.

I won't have time to investigate for a few more weeks, but I thought I would report this now since (a) it obviously needs a closer look before we release v0.4, and (b) @caspervdw might brilliantly think of the cause and save me some work 😉 .

**Comment by caspervdw** [comment]
@nkeim I seem to have missed your issue, sorry! The unittests have apparently missed an edge case, good that this came up before the release. 

For sure the prediction and `adaptive_step` are the newest and least tested parts. I suggest turning them off independently so that we might narrow down the issue to one of them (and hopefully not the core linking code!). Do you have `memory` on? That might be a third thing to turn off/on. Without these tests I have no clue where to start looking.

**Comment by nkeim** [comment]
@caspervdw agreed, those are the likely culprit. I did not have memory turned on. I think the best way is to turn on prediction diagnostics and then run it on the real data, and hope that I can identify the anomaly with `pdb`, or at least extract enough state to make it reproducible quickly. 

This is creeping toward the top of my to-do list!

**Comment by caspervdw** [comment]
@nkeim any results yet? Would be nice to release v0.4 soon!

**Comment by nkeim** [comment]
@caspervdw Today I'm working on reproducing the bug efficiently.

**Comment by caspervdw** [comment]
Closing through #477  :tada:
