### ISSUE TITLE
Permission denied when installing

### ISSUE THREAD

**Issue by Craig184** [soft-matter/trackpy#526]
I am a complete novice when it comes to coding. Im trying to install trackpy but it keeps coming up with a permission error, how do i go about getting around this? Thanks in advance for any help. 

[Errno 13] Permission denied: 'C:\\Users\\craig\\Anaconda3\\Lib\\site-packages\\pandas\\_libs\\algos.cp37-win_amd64.pyd'

**Comment by danielballan** [comment]
Hi @Craig184. I don't know much about using Anaconda on Windows. A permissions-related error suggests to me that maybe Anaconda was installed as an Administrator (sometimes labeled "Install for all users") and that now you are trying to modify Anaconda as a mere User. You might try uninstalling Anaconda and re-installing it "for just this user". Or you might try right-clicking on the icon that launches whichever command prompt you are using, and choosing "Run as Administrator".

I can't guarantee that the above advice is any good, and there's some risk it could make things worse, but it's what I would try in your shoes. Having just said that, I Googled "Python Anaconda permission denied" and came across [this well-rated StackOverflow post](https://stackoverflow.com/a/45065768/1221924) with identical advice, so that's encouraging.

**Comment by Craig184** [comment]
Hi @danielballan . Thanks very much for the advice. It worked in so much as it solved the original error but im now faced with a type error shown below. Any further advice would be much appreciated

TypeErrorTraceback (most recent call last)
<ipython-input-1-81f6999da9dc> in <module>()
----> 1 import trackpy

C:\Users\craig\Anaconda\lib\site-packages\trackpy\__init__.pyc in <module>()
      9 del get_versions
     10 
---> 11 from trackpy.api import *
     12 
     13 handle_logging()

C:\Users\craig\Anaconda\lib\site-packages\trackpy\api.py in <module>()
      8            direction_corr, is_typical, diagonal_size
      9 from .static import proximity, pair_correlation_2d, pair_correlation_3d
---> 10 from .plots import annotate, annotate3d, plot_traj, ptraj, \
     11            plot_displacements, subpx_bias, mass_size, mass_ecc, \
     12            scatter, scatter3d, plot_traj3d, ptraj3d, plot_density_profile

C:\Users\craig\Anaconda\lib\site-packages\trackpy\plots.py in <module>()
     13 
     14 try:
---> 15     from pims import plot_to_frame, plots_to_frame, normalize
     16 except ImportError:
     17     plot_to_frame = None

C:\Users\craig\Anaconda\lib\site-packages\pims\__init__.py in <module>()
----> 1 from pims.api import *
      2 
      3 from ._version import get_versions
      4 __version__ = get_versions()['version']
      5 del get_versions

C:\Users\craig\Anaconda\lib\site-packages\pims\api.py in <module>()
      3 
      4 from slicerator import pipeline
----> 5 from pims.base_frames import FramesSequence, FramesSequenceND
      6 from pims.frame import Frame
      7 from pims.display import (export, play, scrollable_stack, to_rgb, normalize,

C:\Users\craig\Anaconda\lib\site-packages\pims\base_frames.py in <module>()
     14 
     15 
---> 16 class FramesStream(with_metaclass(ABCMeta, object)):
     17     """
     18     A base class for wrapping input data which knows how to

C:\Users\craig\Anaconda\lib\abc.pyc in __new__(mcls, name, bases, namespace)
     85 
     86     def __new__(mcls, name, bases, namespace):
---> 87         cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
     88         # Compute set of abstract method names
     89         abstracts = set(name

TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by ludjam** [comment]
Hey,
I have exactly the same problem than @Craig184 (described on the January 30th) on a computer at work on which I don't have administrator rights (but I could install anaconda locally without administrator login). It works perfectly on my personal windows computer. 
If you have any suggestions to try to fix that, it would helps me a lot. =)

**Comment by ludjam** [comment]
Hello,
I finally manage to get rid of this problem. Getting an administrator login didn't change anything. But chosing to install trackpy with the comand "conda install -c conda-forge trackpy" as presented on anaconda website instead of "conda update -c soft-matter trackpy" from soft-matter website solved my problem ! The latter conducted to total dowgrade of my anaconda installation with only python 2 which caused a lot of compatibility problems.

**Comment by nkeim** [comment]
That's good to hear, and thank you so much for the follow-up! @ludjam where did you see the instruction to use the `soft-matter` channel? We have been trying to phase it out.

**Comment by ludjam** [comment]
Here: [https://soft-matter.github.io/trackpy/v0.3.0/installation.html](https://soft-matter.github.io/trackpy/v0.3.0/installation.html) =)

**Comment by nkeim** [comment]
Thanks. The latest trackpy version is 0.4.1, and we removed the `soft-matter` channel from the instructions back in 2016. But those old docs still show up a lot in searches.

You can always find the docs for the latest release at https://soft-matter.github.io/trackpy/ , or linked from the GitHub page.

Read the Docs adds a warning banner to old versions, but I don't see an easy way to do that in this scenario. That's unfortunate.
