### ISSUE TITLE
trackpy in 3D color tracking

### ISSUE THREAD

**Issue by ravidraj10** [soft-matter/trackpy#533]
I am tracking multiple particle-like colored objects using trackpy. The problem is I am not able to track the color of the feature. There are two colored objects present in the 3D images.

**Comment by nkeim** [comment]
Hi! Sorry for the long wait; I hope you were able to solve your problem another way. The linking algorithm is n-dimensional, so trackpy lets you track any other attribute of your objects (size, color, shape, whatever) if you can treat it like a coordinate. So if you can assign a scalar value `color` based on color, then you can set the coordinates for linking to be `[x, y, z, color]`. You need to scale `color` so that it varies by the same magnitude as the other coordinates; i.e. typical error in `color` should be significantly smaller than `search_range`, and typical difference in `color` between different objects should be ≥ `search_range`.
