### ISSUE TITLE
Video with tracks exporting

### ISSUE THREAD

**Issue by MirSA93** [soft-matter/trackpy#547]
Hello there,

I am new to programming\trackpy and currently trying to export a video file with calculated tracks shown on it. I have tried multiple codes suggested online but i am always getting an empty file.
this is one of the codes i have tried previously.

`    images = [img for img in os.listdir(r'C:\Users\alsaad09\Desktop\M1 IMS') if img.endswith(".png")]
    frame = cv2.imread(os.path.join(r'C:\Users\alsaad09\Desktop\M1 IMS', images[0]))
    height, width, layers = frame.shape
    video = cv2.VideoWriter(r'C:\Users\alsaad09\Desktop\analysis\trail2.avi', -1, 60, (10,5)) 

    for image in images:
        video.write(cv2.imread(os.path.join(r'C:\Users\alsaad09\Desktop\M1 IMS', image)))  
        print(image)
        cv2.destroyAllWindows()
        video.release()
  `

Any suggestions?

Thanks in advance!

**Comment by nkeim** [comment]
I often use [`pims`](https://github.com/soft-matter/pims), which in this case acts as a very inefficient (but easy) way to use `ffmpeg`:

```python
import pims
pims.display.export_pyav(pims.open('*.png'), 'movie.mov', 
                         rate=15, codec='libx264')
```

You can also just use ffmpeg directly, which involves minimal dependencies. You can install it from conda-forge.

Note that if you have the latest versions of PyAV, etc., you currently need the [development version](http://soft-matter.github.io/pims/v0.4.1/install.html#development-version) of pims

I'm going to close this issue since it should either continue as a pims issue, or on e.g. Stack Overflow (depending on what you try).
